<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Reddcoin wallet & staking user interface - StakeUI">
    <meta name="author" content="Convertor">
    <link rel="icon" href="/tpl/img/smallLogoRDD.png">

    <title>Reddcoin StakeUI</title>
    <link href="/tpl/css/bootstrap.min.css" rel="stylesheet">
    <link href="/tpl/css/staking.css" rel="stylesheet">

    <?php if (!is_null(Flight::get('chart'))) { ?>
    <script>
      window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer",
    {
        zoomEnabled: true,
        animationEnabled: true,
        backgroundColor: null,
        exportEnabled: true,
        axisX:{      
            valueFormatString: "YYYY-MM-DD hh:mm TT" ,
        },
       data: [
      {
        type: "splineArea",
        
        dataPoints: [
        <?php foreach (Flight::get('chart') as $chart) { $chart['time'] = date('Y, m, d, H, i', strtotime("-1 month", $chart['time']));
            echo "{ x: new Date({$chart['time']}), y: {$chart[Flight::get('chartSelect')]} },";
        } ?>
        ]
      }
      ]
    });

    chart.render();
  }
</script>

<?php } ?>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/overview">StakeUI</a>
          <?php if($_SESSION['vers'] != VERS) { ?>
            <a class="navbar-brand" href="https://github.com/Reddhead-devs/StakeUI"><small style="color: red;">Update available</small></a>
          <?php } ?>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          </ul>
          <div class="navbar-right">
            <ul class="nav navbar-nav">
                <li><a><small>Enabled: <span style="color: <?php echo (Flight::get('getstaking')['enabled']) ? 'green': 'red'; ?>;" class="glyphicon glyphicon-<?php echo (Flight::get('getstaking')['enabled']) ? 'ok': 'remove'; ?>" aria-hidden="true"></span></small></a></li>
                <li><a><small>Staking: <span style="color: <?php echo (Flight::get('getstaking')['staking']) ? 'green': 'red'; ?>;" class="glyphicon glyphicon-<?php echo (Flight::get('getstaking')['staking']) ? 'ok': 'remove'; ?>" aria-hidden="true"></span></small></a></li>
                <li><a><small>Total weight: <?php echo number_format(Flight::get('getstaking')['totalweight']); ?></small></a></li>
                <li><a><small>Average weight: <?php echo number_format(Flight::get('getstaking')['averageweight']); ?></small></a></li>
                <li><a><small>Network weight: <?php echo number_format(Flight::get('getstaking')['netstakeweight']); ?></small></a></li>
                <li><a><small>Price: <?php echo $_SESSION['reddex'][Flight::get('currency')] . ' ' . Flight::get('currencySym'); ?></small></a></li>
		    </ul>
        </div>
        </div>
      </div>
    </nav>

    <div class="container">
