<div class="row">
    <div class="col-md-6">
        <h3>New Account</h3>
        <hr />
        <form class="form-inline text-center" action="/account" method="POST">
            <div class="form-group">
                <input type="text" class="form-control" id="account" name="account" placeholder="Account name">
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
    <div class="col-md-6">
        <table class='table-striped table-bordered table table-hover'>
            <thead><tr><th>Account</th><th>Balance</th><th></th></tr></thead>
            <?php foreach(Flight::reddcoin()->listaccounts() as $account => $balance) { ?>
                <tr><td><a href="myaddresses/<?php echo ($account == '') ? 'Default' : $account; ?>"><?php echo ($account == '') ? 'Default' : $account; ?></a> <small>(<?php echo count(Flight::reddcoin()->getaddressesbyaccount($account)); ?> addresses)</small></td><td><?php echo number_format($balance,8); ?> &#588;</td><td><a href="address/<?php echo ($account == '') ? 'Default' : $account; ?>" class="btn btn-success btn-xs">New address</a></td></tr>
            <?php } ?>
        </table>
    </div>
</div>